// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: category.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createPostCategories = `-- name: CreatePostCategories :many
WITH Category_CTE AS (
  SELECT id, name FROM categories
  WHERE id = ANY($1::bigint[])
),
Values_CTE AS (
  SELECT p.post_id, cc.id category_id FROM (
    SELECT id post_id FROM posts WHERE id = $2::bigint
  ) p
  CROSS JOIN Category_CTE cc
),
Ins_CTE AS (
  INSERT INTO post_categories (post_id, category_id)
  SELECT post_id, category_id FROM Values_CTE
  ON CONFLICT (post_id, category_id) DO NOTHING
)
SELECT id, name FROM Category_CTE
`

type CreatePostCategoriesParams struct {
	CategoryIds []int64 `json:"category_ids"`
	PostID      int64   `json:"post_id"`
}

type CreatePostCategoriesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreatePostCategories(ctx context.Context, arg CreatePostCategoriesParams) ([]CreatePostCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, createPostCategories, pq.Array(arg.CategoryIds), arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreatePostCategoriesRow{}
	for rows.Next() {
		var i CreatePostCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategories = `-- name: DeleteCategories :execrows
DELETE FROM categories WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteCategories(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategories, pq.Array(ids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePostCategories = `-- name: DeletePostCategories :exec
DELETE FROM post_categories
WHERE post_id = $1::bigint
  AND category_id <> ALL($2::bigint[])
`

type DeletePostCategoriesParams struct {
	PostID      int64   `json:"post_id"`
	CategoryIds []int64 `json:"category_ids"`
}

func (q *Queries) DeletePostCategories(ctx context.Context, arg DeletePostCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, deletePostCategories, arg.PostID, pq.Array(arg.CategoryIds))
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT id, name FROM categories
ORDER BY id ASC
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostCategories = `-- name: GetPostCategories :many
SELECT id, name FROM categories
WHERE id = ANY(
  SELECT category_id FROM post_categories
  WHERE post_id = $1
)
`

func (q *Queries) GetPostCategories(ctx context.Context, postID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getPostCategories, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.name,
  (SELECT count(*) FROM post_categories
    WHERE category_id = c.id) post_count
FROM categories c
ORDER BY
  CASE WHEN $1::bool THEN name END ASC,
  CASE WHEN $2::bool THEN name END DESC,
  id ASC
`

type ListCategoriesParams struct {
	NameAsc  bool `json:"name_asc"`
	NameDesc bool `json:"name_desc"`
}

type ListCategoriesRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	PostCount int64  `json:"post_count"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.NameAsc, arg.NameDesc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2::varchar
WHERE id = $1 RETURNING id, name
`

type UpdateCategoryParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
